package strategy

// Breakout / Volatility Expansion strategies (IDs 51-70).

import (
	c "github.com/algomatic/strats100/go-strats/pkg/conditions"
	"github.com/algomatic/strats100/go-strats/pkg/types"
)

func breakoutStrategies() []*types.StrategyDef {
	return []*types.StrategyDef{
		// 51: Donchian 20 High/Low Breakout
		{
			ID: 51, Name: "donchian_20_breakout",
			DisplayName: "Donchian 20 High/Low Breakout",
			Philosophy:  "Classic channel breakout captures new highs/lows as trend initiators.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "breakout", "atr_stop", "atr_target", "MAX", "MIN", "ATR", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.BreaksAboveLevel("donchian_high_20")},
			EntryShort: []types.ConditionFn{c.BreaksBelowLevel("donchian_low_20")},
			ExitLong:   []types.ConditionFn{c.BreaksBelowLevel("donchian_low_20")},
			ExitShort:  []types.ConditionFn{c.BreaksAboveLevel("donchian_high_20")},
			ATRStopMult: 2.0, ATRTargetMult: 4.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"donchian_high_20", "donchian_low_20", "atr_14"},
		},
		// 52: Donchian + ATR Filter
		{
			ID: 52, Name: "donchian_atr_filter",
			DisplayName: "Donchian + ATR Filter",
			Philosophy:  "Donchian breakout filtered by expanded range confirms genuine momentum.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "volatility", "long_short", "breakout", "atr_stop", "MAX", "MIN", "ATR", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.BreaksAboveLevel("donchian_high_20"), c.RangeExceedsATR(1.2)},
			EntryShort: []types.ConditionFn{c.BreaksBelowLevel("donchian_low_20"), c.RangeExceedsATR(1.2)},
			ExitLong:   []types.ConditionFn{c.BreaksBelowLevel("donchian_low_20")},
			ExitShort:  []types.ConditionFn{c.BreaksAboveLevel("donchian_high_20")},
			TrailingATRMult: 2.0, ATRStopMult: 2.0,
			RequiredIndicators: []string{"donchian_high_20", "donchian_low_20", "atr_14"},
		},
		// 53: BB Upper/Lower Breakout
		{
			ID: 53, Name: "bb_breakout",
			DisplayName: "BB Upper/Lower Breakout",
			Philosophy:  "Bollinger Band breakout with rising width confirms volatility expansion.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "breakout", "atr_stop", "atr_target", "BBANDS", "ATR", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.Above("close", c.ColRef("bb_upper")), c.Rising("bb_width", 3)},
			EntryShort: []types.ConditionFn{c.Below("close", c.ColRef("bb_lower")), c.Rising("bb_width", 3)},
			ExitLong:   []types.ConditionFn{c.Below("close", c.ColRef("bb_middle"))},
			ExitShort:  []types.ConditionFn{c.Above("close", c.ColRef("bb_middle"))},
			ATRStopMult: 2.0, ATRTargetMult: 3.0,
			RequiredIndicators: []string{"close", "bb_upper", "bb_lower", "bb_middle", "bb_width", "atr_14"},
		},
		// 54: BB Squeeze Breakout (classic)
		{
			ID: 54, Name: "bb_squeeze_breakout",
			DisplayName: "BB Squeeze Breakout",
			Philosophy:  "Bollinger squeeze identifies low-volatility consolidation; breakout signals expansion.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "volatility", "long_short", "breakout", "atr_stop", "BBANDS", "ATR", "vol_contract_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.Squeeze("bb_width", 60), c.Above("close", c.ColRef("bb_upper"))},
			EntryShort: []types.ConditionFn{c.Squeeze("bb_width", 60), c.Below("close", c.ColRef("bb_lower"))},
			ExitLong:   []types.ConditionFn{c.Below("close", c.ColRef("bb_middle"))},
			ExitShort:  []types.ConditionFn{c.Above("close", c.ColRef("bb_middle"))},
			TrailingATRMult: 2.0, ATRStopMult: 2.0,
			RequiredIndicators: []string{"close", "bb_upper", "bb_lower", "bb_middle", "bb_width", "atr_14"},
		},
		// 55: ATR Channel Breakout
		{
			ID: 55, Name: "atr_channel_breakout",
			DisplayName: "ATR Channel Breakout",
			Philosophy:  "Price breaking beyond ATR-scaled SMA channel signals strong directional momentum.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "breakout", "atr_stop", "atr_target", "ATR", "SMA", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.BreaksAboveSMAEnvelope("sma_20", 2.0)},
			EntryShort: []types.ConditionFn{c.BreaksBelowSMAEnvelope("sma_20", 2.0)},
			ExitLong:   []types.ConditionFn{c.Below("close", c.ColRef("sma_20"))},
			ExitShort:  []types.ConditionFn{c.Above("close", c.ColRef("sma_20"))},
			ATRStopMult: 2.5, ATRTargetMult: 4.0,
			RequiredIndicators: []string{"sma_20", "atr_14"},
		},
		// 56: Range Expansion Day Breakout
		{
			ID: 56, Name: "range_expansion_breakout",
			DisplayName: "Range Expansion Day Breakout",
			Philosophy:  "Extreme range expansion with directional close signals institutional activity.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "volatility", "long_short", "breakout", "time", "atr_stop", "ATR", "vol_expand", "scalp"},
			EntryLong:  []types.ConditionFn{c.RangeExceedsATR(1.8), c.InTopPctOfRange(0.20)},
			EntryShort: []types.ConditionFn{c.RangeExceedsATR(1.8), c.InBottomPctOfRange(0.20)},
			TrailingATRMult: 1.5, ATRStopMult: 1.5, TimeStopBars: 10,
			RequiredIndicators: []string{"atr_14"},
		},
		// 57: Opening Range Breakout Proxy
		{
			ID: 57, Name: "opening_range_breakout",
			DisplayName: "Opening Range Breakout Proxy",
			Philosophy:  "Proxy of opening range using Donchian channels captures early-session momentum.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "breakout", "time", "MAX", "MIN", "ATR", "vol_expand", "scalp"},
			EntryLong:  []types.ConditionFn{c.BreaksAboveLevel("donchian_high_5")},
			EntryShort: []types.ConditionFn{c.BreaksBelowLevel("donchian_low_5")},
			TrailingATRMult: 1.5, ATRStopMult: 1.5, TimeStopBars: 15,
			RequiredIndicators: []string{"donchian_high_5", "donchian_low_5", "atr_14"},
		},
		// 58: Volatility Step-Up + Break
		{
			ID: 58, Name: "vol_stepup_break",
			DisplayName: "Volatility Step-Up + Break",
			Philosophy:  "Rising ATR with expanding bands confirms genuine volatility step-up for breakout.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"volatility", "breakout", "long_short", "breakout", "atr_stop", "ATR", "BBANDS", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.Rising("atr_14", 5), c.Rising("bb_width", 5), c.BreaksAboveLevel("donchian_high_10")},
			EntryShort: []types.ConditionFn{c.Rising("atr_14", 5), c.Rising("bb_width", 5), c.BreaksBelowLevel("donchian_low_10")},
			TrailingATRMult: 2.0, ATRStopMult: 2.0,
			RequiredIndicators: []string{"atr_14", "bb_width", "donchian_high_10", "donchian_low_10"},
		},
		// 59: Keltner-style Breakout
		{
			ID: 59, Name: "keltner_breakout",
			DisplayName: "Keltner-style Breakout",
			Philosophy:  "Keltner channel (EMA + ATR) breakout normalizes for volatility, reducing false signals.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "breakout", "atr_stop", "atr_target", "EMA", "ATR", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.CloseAboveUpperChannel("ema_20", 1.5)},
			EntryShort: []types.ConditionFn{c.CloseBelowLowerChannel("ema_20", 1.5)},
			ExitLong:   []types.ConditionFn{c.Below("close", c.ColRef("ema_20"))},
			ExitShort:  []types.ConditionFn{c.Above("close", c.ColRef("ema_20"))},
			ATRStopMult: 2.0, ATRTargetMult: 3.0,
			RequiredIndicators: []string{"ema_20", "atr_14"},
		},
		// 60: ADX Breakout (trend ignition)
		{
			ID: 60, Name: "adx_breakout",
			DisplayName: "ADX Breakout (trend ignition)",
			Philosophy:  "ADX rising from low levels signals new trend ignition; breakout confirms direction.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "regime", "long_short", "threshold", "atr_stop", "ADX", "MAX", "MIN", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("adx_14", c.NumRef(20)), c.BreaksAboveLevel("donchian_high_20")},
			EntryShort: []types.ConditionFn{c.CrossesAbove("adx_14", c.NumRef(20)), c.BreaksBelowLevel("donchian_low_20")},
			TrailingATRMult: 2.0, ATRStopMult: 2.0,
			RequiredIndicators: []string{"adx_14", "donchian_high_20", "donchian_low_20", "atr_14"},
		},
		// 61: RSI Breakout (momentum ignition)
		{
			ID: 61, Name: "rsi_breakout",
			DisplayName: "RSI Breakout (momentum ignition)",
			Philosophy:  "RSI crossing key levels with price breakout confirms momentum ignition.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "threshold", "time", "atr_stop", "RSI", "MAX", "MIN", "ATR", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("rsi_14", c.NumRef(60)), c.BreaksAboveLevel("donchian_high_10")},
			EntryShort: []types.ConditionFn{c.CrossesBelow("rsi_14", c.NumRef(40)), c.BreaksBelowLevel("donchian_low_10")},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("rsi_14", c.NumRef(50))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("rsi_14", c.NumRef(50))},
			ATRStopMult: 2.0, TimeStopBars: 25,
			RequiredIndicators: []string{"rsi_14", "donchian_high_10", "donchian_low_10", "atr_14"},
		},
		// 62: MACD Breakout Confirmation
		{
			ID: 62, Name: "macd_breakout_confirmation",
			DisplayName: "MACD Breakout Confirmation",
			Philosophy:  "Price breakout confirmed by MACD alignment reduces false breakout risk.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "breakout", "atr_stop", "MACD", "MAX", "MIN", "ATR", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.BreaksAboveLevel("donchian_high_20"), c.Above("macd", c.NumRef(0))},
			EntryShort: []types.ConditionFn{c.BreaksBelowLevel("donchian_low_20"), c.Below("macd", c.NumRef(0))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("macd", c.NumRef(0))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("macd", c.NumRef(0))},
			TrailingATRMult: 2.0, ATRStopMult: 2.0,
			RequiredIndicators: []string{"donchian_high_20", "donchian_low_20", "macd", "atr_14"},
		},
		// 63: Bollinger Walk the Band
		{
			ID: 63, Name: "bb_walk_the_band",
			DisplayName: "Bollinger Walk the Band",
			Philosophy:  "Consecutive closes beyond Bollinger Band signal persistent trend momentum.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "trend", "long_short", "threshold", "trailing", "BBANDS", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.HeldForNBars("close", func(v float64) bool { return true }, 1), c.Above("close", c.ColRef("bb_upper")), c.ConsecutiveHigherCloses(3)},
			EntryShort: []types.ConditionFn{c.Below("close", c.ColRef("bb_lower")), c.ConsecutiveLowerCloses(3)},
			ExitLong:   []types.ConditionFn{c.Below("close", c.ColRef("bb_upper"))},
			ExitShort:  []types.ConditionFn{c.Above("close", c.ColRef("bb_lower"))},
			TrailingATRMult: 2.0, ATRStopMult: 2.0,
			RequiredIndicators: []string{"close", "bb_upper", "bb_lower", "atr_14"},
		},
		// 64: Pivot Breakout
		{
			ID: 64, Name: "pivot_breakout",
			DisplayName: "Pivot Breakout",
			Philosophy:  "Pivot level breakout captures intraday directional momentum.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "breakout", "time", "SMA", "ATR", "vol_expand", "scalp"},
			EntryLong:  []types.ConditionFn{c.CloseAboveUpperChannel("typical_price_sma_1", 1.0)},
			EntryShort: []types.ConditionFn{c.CloseBelowLowerChannel("typical_price_sma_1", 1.0)},
			ATRStopMult: 1.5, TimeStopBars: 15,
			RequiredIndicators: []string{"typical_price_sma_1", "atr_14"},
		},
		// 65: VCP Proxy
		{
			ID: 65, Name: "vcp_proxy",
			DisplayName: "Volatility Contraction Pattern Proxy",
			Philosophy:  "Decreasing ATR with higher lows signals coiling energy; breakout captures expansion.",
			Category: "breakout", Direction: types.LongOnly,
			Tags:       []string{"breakout", "volatility", "long_only", "breakout", "atr_stop", "ATR", "MAX", "vol_contract_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.Falling("atr_14", 10), c.BreaksAboveLevel("donchian_high_20")},
			TrailingATRMult: 2.0, ATRStopMult: 2.0,
			RequiredIndicators: []string{"atr_14", "donchian_high_20"},
		},
		// 66: Gap + Go
		{
			ID: 66, Name: "gap_and_go",
			DisplayName: "Gap + Go",
			Philosophy:  "Gaps backed by directional close signal continuation momentum.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "breakout", "time", "ATR", "vol_expand", "scalp"},
			EntryLong:  []types.ConditionFn{c.GapUp(1.0), c.Above("close", c.ColRef("open"))},
			EntryShort: []types.ConditionFn{c.GapDown(1.0), c.Below("close", c.ColRef("open"))},
			TrailingATRMult: 1.5, ATRStopMult: 1.5, TimeStopBars: 10,
			RequiredIndicators: []string{"open", "close", "atr_14"},
		},
		// 67: Inside Bar Breakout
		{
			ID: 67, Name: "inside_bar_breakout",
			DisplayName: "Inside Bar Breakout",
			Philosophy:  "Narrowest range bar signals compression; breakout captures directional expansion.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "pattern", "long_short", "pattern", "breakout", "time", "ATR", "vol_contract_expand", "scalp"},
			EntryLong:  []types.ConditionFn{c.NarrowestRange(7), c.Above("close", c.ColRef("high"))},
			EntryShort: []types.ConditionFn{c.NarrowestRange(7), c.Below("close", c.ColRef("low"))},
			ATRStopMult: 1.5, ATRTargetMult: 2.5, TimeStopBars: 10,
			RequiredIndicators: []string{"atr_14"},
		},
		// 68: 1-2-3 Breakout
		{
			ID: 68, Name: "one_two_three_breakout",
			DisplayName: "1-2-3 Breakout",
			Philosophy:  "Swing low formation then break above pullback high signals trend continuation.",
			Category: "breakout", Direction: types.LongOnly,
			Tags:       []string{"breakout", "long_only", "breakout", "atr_stop", "MAX", "MIN", "ATR", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.Rising("close", 2), c.BreaksAboveLevel("donchian_high_10")},
			ATRStopMult: 2.0, ATRTargetMult: 3.0,
			RequiredIndicators: []string{"donchian_high_10", "atr_14"},
		},
		// 69: ATR Trailing Breakout
		{
			ID: 69, Name: "atr_trailing_breakout",
			DisplayName: "ATR Trailing Breakout",
			Philosophy:  "Close exceeding prior close by full ATR signals strong momentum thrust.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "breakout", "trailing", "ATR", "vol_expand", "swing"},
			EntryLong: []types.ConditionFn{c.CloseAboveUpperChannel("close", 1.0)},
			EntryShort: []types.ConditionFn{c.CloseBelowLowerChannel("close", 1.0)},
			TrailingATRMult: 2.0, ATRStopMult: 2.0, TimeStopBars: 20,
			RequiredIndicators: []string{"atr_14"},
		},
		// 70: CMO Breakout
		{
			ID: 70, Name: "cmo_breakout",
			DisplayName: "Chande Momentum Oscillator Breakout",
			Philosophy:  "Strong CMO reading with price breakout confirms momentum-driven move.",
			Category: "breakout", Direction: types.LongShort,
			Tags:       []string{"breakout", "long_short", "threshold", "time", "CMO", "MAX", "MIN", "ATR", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.Above("cmo_14", c.NumRef(40)), c.BreaksAboveLevel("donchian_high_10")},
			EntryShort: []types.ConditionFn{c.Below("cmo_14", c.NumRef(-40)), c.BreaksBelowLevel("donchian_low_10")},
			ExitLong:   []types.ConditionFn{c.Below("cmo_14", c.NumRef(10))},
			ExitShort:  []types.ConditionFn{c.Above("cmo_14", c.NumRef(-10))},
			ATRStopMult: 2.0,
			RequiredIndicators: []string{"cmo_14", "donchian_high_10", "donchian_low_10", "atr_14"},
		},
	}
}
