package strategy

// Mean reversion strategies (IDs 26-50).

import (
	c "github.com/algomatic/strats100/go-strats/pkg/conditions"
	"github.com/algomatic/strats100/go-strats/pkg/types"
)

func meanReversionStrategies() []*types.StrategyDef {
	return []*types.StrategyDef{
		// 26: RSI Oversold Bounce
		{
			ID: 26, Name: "rsi_oversold_bounce",
			DisplayName: "RSI Oversold Bounce",
			Philosophy:  "Buy oversold dips in uptrending markets for mean reversion to the norm.",
			Category: "mean_reversion", Direction: types.LongOnly,
			Tags:       []string{"mean_reversion", "long_only", "threshold", "atr_stop", "atr_target", "RSI", "SMA", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Above("close", c.ColRef("sma_200")), c.CrossesAbove("rsi_14", c.NumRef(30))},
			ExitLong:   []types.ConditionFn{c.Above("rsi_14", c.NumRef(55))},
			ATRStopMult: 2.0, ATRTargetMult: 2.5, TimeStopBars: 20,
			RequiredIndicators: []string{"close", "sma_200", "rsi_14", "atr_14"},
		},
		// 27: RSI Overbought Fade
		{
			ID: 27, Name: "rsi_overbought_fade",
			DisplayName: "RSI Overbought Fade",
			Philosophy:  "Fade overbought rallies in downtrending markets for mean reversion.",
			Category: "mean_reversion", Direction: types.ShortOnly,
			Tags:       []string{"mean_reversion", "short_only", "threshold", "atr_stop", "atr_target", "RSI", "SMA", "ATR", "range_favor", "swing"},
			EntryShort: []types.ConditionFn{c.Below("close", c.ColRef("sma_200")), c.CrossesBelow("rsi_14", c.NumRef(70))},
			ExitShort:  []types.ConditionFn{c.Below("rsi_14", c.NumRef(45))},
			ATRStopMult: 2.0, ATRTargetMult: 2.5,
			RequiredIndicators: []string{"close", "sma_200", "rsi_14", "atr_14"},
		},
		// 28: Bollinger Band Reversion to Middle
		{
			ID: 28, Name: "bb_reversion_middle",
			DisplayName: "Bollinger Band Reversion to Middle",
			Philosophy:  "Price bouncing off Bollinger extremes tends to revert toward the middle band.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "threshold", "signal", "time", "BBANDS", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("close", c.ColRef("bb_lower"))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("close", c.ColRef("bb_upper"))},
			ExitLong:   []types.ConditionFn{c.CrossesAbove("close", c.ColRef("bb_middle"))},
			ExitShort:  []types.ConditionFn{c.CrossesBelow("close", c.ColRef("bb_middle"))},
			ATRStopMult: 2.0, TimeStopBars: 20,
			RequiredIndicators: []string{"close", "bb_upper", "bb_middle", "bb_lower", "atr_14"},
		},
		// 29: Bollinger Double Tap Fade
		{
			ID: 29, Name: "bb_double_tap_fade",
			DisplayName: "Bollinger Double Tap Fade",
			Philosophy:  "Multiple touches of Bollinger extremes with RSI confirmation increase reversion probability.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "threshold", "atr_stop", "atr_target", "BBANDS", "RSI", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.DoubleTapBelowBB(5), c.Below("rsi_14", c.NumRef(35)), c.CrossesAbove("close", c.ColRef("bb_lower"))},
			EntryShort: []types.ConditionFn{c.DoubleTapAboveBB(5), c.Above("rsi_14", c.NumRef(65)), c.CrossesBelow("close", c.ColRef("bb_upper"))},
			ExitLong:   []types.ConditionFn{c.CrossesAbove("close", c.ColRef("bb_middle"))},
			ExitShort:  []types.ConditionFn{c.CrossesBelow("close", c.ColRef("bb_middle"))},
			ATRStopMult: 2.0, ATRTargetMult: 3.0,
			RequiredIndicators: []string{"close", "bb_upper", "bb_middle", "bb_lower", "rsi_14", "atr_14"},
		},
		// 30: Stoch Oversold/Overbought Cross
		{
			ID: 30, Name: "stoch_oversold_overbought",
			DisplayName: "Stoch Oversold/Overbought Cross",
			Philosophy:  "Stochastic crossovers at extreme zones signal short-term exhaustion and reversion.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "cross", "signal", "time", "STOCH", "ATR", "range_favor", "scalp"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("stoch_k", c.ColRef("stoch_d")), c.Below("stoch_k", c.NumRef(20)), c.Below("stoch_d", c.NumRef(20))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("stoch_k", c.ColRef("stoch_d")), c.Above("stoch_k", c.NumRef(80)), c.Above("stoch_d", c.NumRef(80))},
			ExitLong:   []types.ConditionFn{c.Above("stoch_k", c.NumRef(50))},
			ExitShort:  []types.ConditionFn{c.Below("stoch_k", c.NumRef(50))},
			ATRStopMult: 1.5, TimeStopBars: 10,
			RequiredIndicators: []string{"stoch_k", "stoch_d", "atr_14"},
		},
		// 31: Williams %R Snapback
		{
			ID: 31, Name: "willr_snapback",
			DisplayName: "Williams %R Snapback",
			Philosophy:  "Williams %R extreme reversals capture quick snapback momentum.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "threshold", "time", "WILLR", "ATR", "range_favor", "scalp"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("willr_14", c.NumRef(-80))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("willr_14", c.NumRef(-20))},
			ExitLong:   []types.ConditionFn{c.Above("willr_14", c.NumRef(-50))},
			ExitShort:  []types.ConditionFn{c.Below("willr_14", c.NumRef(-50))},
			ATRStopMult: 1.5, TimeStopBars: 8,
			RequiredIndicators: []string{"willr_14", "atr_14"},
		},
		// 32: CCI +/-100 Reversion
		{
			ID: 32, Name: "cci_reversion",
			DisplayName: "CCI +/-100 Reversion",
			Philosophy:  "CCI crossing back through extremes signals momentum exhaustion and reversion.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "threshold", "signal", "time", "CCI", "ATR", "range_favor", "scalp"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("cci_20", c.NumRef(-100))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("cci_20", c.NumRef(100))},
			ExitLong:   []types.ConditionFn{c.Above("cci_20", c.NumRef(0))},
			ExitShort:  []types.ConditionFn{c.Below("cci_20", c.NumRef(0))},
			ATRStopMult: 1.5, TimeStopBars: 12,
			RequiredIndicators: []string{"cci_20", "atr_14"},
		},
		// 33: MFI Extreme Fade
		{
			ID: 33, Name: "mfi_extreme_fade",
			DisplayName: "MFI Extreme Fade",
			Philosophy:  "Money Flow Index extremes combine price and volume for higher-quality reversion signals.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "volume_flow", "long_short", "threshold", "time", "MFI", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("mfi_14", c.NumRef(20))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("mfi_14", c.NumRef(80))},
			ExitLong:   []types.ConditionFn{c.Above("mfi_14", c.NumRef(50))},
			ExitShort:  []types.ConditionFn{c.Below("mfi_14", c.NumRef(50))},
			ATRStopMult: 2.0, TimeStopBars: 20,
			RequiredIndicators: []string{"mfi_14", "atr_14"},
		},
		// 34: RSI(2) Quick Mean Reversion
		{
			ID: 34, Name: "rsi2_quick_mean_reversion",
			DisplayName: "RSI(2) Quick Mean Reversion",
			Philosophy:  "Ultra-short RSI(2) extremes capture quick snapback moves with tight risk.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "threshold", "time", "RSI", "SMA", "ATR", "range_favor", "scalp", "tight"},
			EntryLong:  []types.ConditionFn{c.Below("rsi_2", c.NumRef(5)), c.Above("close", c.ColRef("sma_50"))},
			EntryShort: []types.ConditionFn{c.Above("rsi_2", c.NumRef(95)), c.Below("close", c.ColRef("sma_50"))},
			ExitLong:   []types.ConditionFn{c.Above("rsi_2", c.NumRef(60))},
			ExitShort:  []types.ConditionFn{c.Below("rsi_2", c.NumRef(40))},
			ATRStopMult: 1.0, TimeStopBars: 5,
			RequiredIndicators: []string{"rsi_2", "close", "sma_50", "atr_14"},
		},
		// 35: Price vs EMA Deviation Reversion
		{
			ID: 35, Name: "price_ema_deviation",
			DisplayName: "Price vs EMA Deviation Reversion",
			Philosophy:  "Extreme price deviation from EMA signals rubber-band snap-back potential.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "threshold", "atr_stop", "atr_target", "EMA", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.DeviationBelow("close", "ema_20", 2.0)},
			EntryShort: []types.ConditionFn{c.DeviationAbove("close", "ema_20", 2.0)},
			ExitLong:   []types.ConditionFn{c.Above("close", c.ColRef("ema_20"))},
			ExitShort:  []types.ConditionFn{c.Below("close", c.ColRef("ema_20"))},
			ATRStopMult: 2.0, ATRTargetMult: 2.0,
			RequiredIndicators: []string{"close", "ema_20", "atr_14"},
		},
		// 36: Z-Score of Close vs SMA20
		{
			ID: 36, Name: "zscore_sma20",
			DisplayName: "Z-Score of Close vs SMA20",
			Philosophy:  "Statistical extremes (z-score beyond 2) with RSI confirmation signal reversion.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "threshold", "time", "SMA", "STDDEV", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Below("zscore_20", c.NumRef(-2)), c.Rising("rsi_14", 2)},
			EntryShort: []types.ConditionFn{c.Above("zscore_20", c.NumRef(2)), c.Falling("rsi_14", 2)},
			ExitLong:   []types.ConditionFn{c.Above("zscore_20", c.NumRef(0))},
			ExitShort:  []types.ConditionFn{c.Below("zscore_20", c.NumRef(0))},
			ATRStopMult: 2.0, TimeStopBars: 20,
			RequiredIndicators: []string{"zscore_20", "rsi_14", "atr_14"},
		},
		// 37: BB Squeeze Fade First Expansion
		{
			ID: 37, Name: "bb_squeeze_fade",
			DisplayName: "BB Squeeze Fade First Expansion",
			Philosophy:  "After extreme compression, the first breakout often fails; fading it captures the snap back.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "volatility", "long_short", "threshold", "atr_stop", "BBANDS", "ATR", "vol_contract", "scalp"},
			EntryLong:  []types.ConditionFn{c.Squeeze("bb_width", 50), c.Below("close", c.ColRef("bb_lower"))},
			EntryShort: []types.ConditionFn{c.Squeeze("bb_width", 50), c.Above("close", c.ColRef("bb_upper"))},
			ExitLong:   []types.ConditionFn{c.CrossesAbove("close", c.ColRef("bb_middle"))},
			ExitShort:  []types.ConditionFn{c.CrossesBelow("close", c.ColRef("bb_middle"))},
			ATRStopMult: 2.0, TimeStopBars: 10,
			RequiredIndicators: []string{"close", "bb_upper", "bb_middle", "bb_lower", "bb_width", "atr_14"},
		},
		// 38: Donchian Middle Reversion
		{
			ID: 38, Name: "donchian_middle_reversion",
			DisplayName: "Donchian Middle Reversion",
			Philosophy:  "Range-bound price reverting from Donchian extremes toward the midpoint.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "pullback", "time", "MAX", "MIN", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("close", c.ColRef("donchian_low_20"))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("close", c.ColRef("donchian_high_20"))},
			ExitLong:   []types.ConditionFn{c.Above("close", c.ColRef("donchian_mid_20"))},
			ExitShort:  []types.ConditionFn{c.Below("close", c.ColRef("donchian_mid_20"))},
			ATRStopMult: 2.0, TimeStopBars: 20,
			RequiredIndicators: []string{"donchian_high_20", "donchian_low_20", "donchian_mid_20", "atr_14"},
		},
		// 39: RSI Divergence
		{
			ID: 39, Name: "rsi_divergence",
			DisplayName: "RSI Divergence",
			Philosophy:  "Price-RSI divergence reveals waning momentum; reversion follows as trend exhausts.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "divergence", "signal", "time", "RSI", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.BullishDivergence("rsi_14", 5), c.Below("rsi_14", c.NumRef(40))},
			EntryShort: []types.ConditionFn{c.BearishDivergence("rsi_14", 5), c.Above("rsi_14", c.NumRef(60))},
			ExitLong:   []types.ConditionFn{c.CrossesAbove("rsi_14", c.NumRef(50))},
			ExitShort:  []types.ConditionFn{c.CrossesBelow("rsi_14", c.NumRef(50))},
			ATRStopMult: 2.0, TimeStopBars: 25,
			RequiredIndicators: []string{"close", "high", "low", "rsi_14", "atr_14"},
		},
		// 40: MACD Divergence
		{
			ID: 40, Name: "macd_divergence",
			DisplayName: "MACD Divergence",
			Philosophy:  "MACD histogram divergence from price signals momentum exhaustion.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "divergence", "signal", "time", "MACD", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.BullishDivergence("macd_hist", 10), c.CrossesAbove("macd_hist", c.NumRef(0))},
			EntryShort: []types.ConditionFn{c.BearishDivergence("macd_hist", 10), c.CrossesBelow("macd_hist", c.NumRef(0))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("macd_hist", c.NumRef(0))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("macd_hist", c.NumRef(0))},
			ATRStopMult: 2.5, TimeStopBars: 30,
			RequiredIndicators: []string{"close", "high", "low", "macd_hist", "atr_14"},
		},
		// 41: Stoch Hook at Extremes
		{
			ID: 41, Name: "stoch_hook_extremes",
			DisplayName: "Stoch Hook at Extremes",
			Philosophy:  "Stochastic turning at extremes captures momentum reversal with tight timing.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "pattern", "time", "STOCH", "range_favor", "scalp"},
			EntryLong:  []types.ConditionFn{c.Below("stoch_k", c.NumRef(20)), c.Rising("stoch_k", 2)},
			EntryShort: []types.ConditionFn{c.Above("stoch_k", c.NumRef(80)), c.Falling("stoch_k", 2)},
			ExitLong:   []types.ConditionFn{c.Above("stoch_k", c.NumRef(50))},
			ExitShort:  []types.ConditionFn{c.Below("stoch_k", c.NumRef(50))},
			ATRStopMult: 1.5, TimeStopBars: 10,
			RequiredIndicators: []string{"stoch_k", "atr_14"},
		},
		// 42: Mean Reversion to VWAP Proxy
		{
			ID: 42, Name: "mean_reversion_vwap_proxy",
			DisplayName: "Mean Reversion to VWAP Proxy",
			Philosophy:  "Deviation from typical price SMA with RSI filter captures intraday reversion.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "threshold", "time", "SMA", "ATR", "range_favor", "scalp"},
			EntryLong:  []types.ConditionFn{c.MeanRevLong("typical_price_sma_20", 1.5), c.Below("rsi_14", c.NumRef(40))},
			EntryShort: []types.ConditionFn{c.MeanRevShort("typical_price_sma_20", 1.5), c.Above("rsi_14", c.NumRef(60))},
			ExitLong:   []types.ConditionFn{c.Above("close", c.ColRef("typical_price_sma_20"))},
			ExitShort:  []types.ConditionFn{c.Below("close", c.ColRef("typical_price_sma_20"))},
			ATRStopMult: 2.0, TimeStopBars: 12,
			RequiredIndicators: []string{"typical_price_sma_20", "rsi_14", "atr_14"},
		},
		// 43: Range Fade with ADX Low
		{
			ID: 43, Name: "range_fade_adx_low",
			DisplayName: "Range Fade with ADX Low",
			Philosophy:  "Low ADX confirms ranging market; RSI extremes signal reversion opportunities.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "regime", "long_short", "threshold", "time", "ADX", "RSI", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Below("adx_14", c.NumRef(15)), c.CrossesAbove("rsi_14", c.NumRef(30))},
			EntryShort: []types.ConditionFn{c.Below("adx_14", c.NumRef(15)), c.CrossesBelow("rsi_14", c.NumRef(70))},
			ExitLong:   []types.ConditionFn{c.Above("rsi_14", c.NumRef(50))},
			ExitShort:  []types.ConditionFn{c.Below("rsi_14", c.NumRef(50))},
			ATRStopMult: 2.0, TimeStopBars: 20,
			RequiredIndicators: []string{"adx_14", "rsi_14", "atr_14"},
		},
		// 44: BB PercentB Reversion
		{
			ID: 44, Name: "bb_percentb_reversion",
			DisplayName: "BB PercentB Reversion",
			Philosophy:  "Bollinger %B crossing back from extremes signals mean reversion momentum.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "threshold", "time", "BBANDS", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("bb_percentb", c.NumRef(0.1))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("bb_percentb", c.NumRef(0.9))},
			ExitLong:   []types.ConditionFn{c.Above("bb_percentb", c.NumRef(0.5))},
			ExitShort:  []types.ConditionFn{c.Below("bb_percentb", c.NumRef(0.5))},
			ATRStopMult: 2.0, TimeStopBars: 20,
			RequiredIndicators: []string{"bb_percentb", "atr_14"},
		},
		// 45: CCI + ATR Exhaustion Fade
		{
			ID: 45, Name: "cci_atr_exhaustion",
			DisplayName: "CCI + ATR Exhaustion Fade",
			Philosophy:  "Extreme CCI with wide range bar signals exhaustion; next close confirms reversal.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "volatility", "long_short", "threshold", "atr_stop", "atr_target", "CCI", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Below("cci_20", c.NumRef(-200)), c.RangeExceedsATR(2.0), c.ConsecutiveHigherCloses(1)},
			EntryShort: []types.ConditionFn{c.Above("cci_20", c.NumRef(200)), c.RangeExceedsATR(2.0), c.ConsecutiveLowerCloses(1)},
			ExitLong:   []types.ConditionFn{c.Above("cci_20", c.NumRef(-100))},
			ExitShort:  []types.ConditionFn{c.Below("cci_20", c.NumRef(100))},
			ATRStopMult: 2.5, ATRTargetMult: 3.0,
			RequiredIndicators: []string{"cci_20", "atr_14"},
		},
		// 46: RSI Midline Range Strategy
		{
			ID: 46, Name: "rsi_midline_range",
			DisplayName: "RSI Midline Range Strategy",
			Philosophy:  "RSI crossing 50 in low-ADX environments captures range momentum.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "cross", "signal", "time", "RSI", "ADX", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Below("adx_14", c.NumRef(20)), c.CrossesAbove("rsi_14", c.NumRef(50))},
			EntryShort: []types.ConditionFn{c.Below("adx_14", c.NumRef(20)), c.CrossesBelow("rsi_14", c.NumRef(50))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("rsi_14", c.NumRef(50))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("rsi_14", c.NumRef(50))},
			ATRStopMult: 2.0, TimeStopBars: 25,
			RequiredIndicators: []string{"adx_14", "rsi_14", "atr_14"},
		},
		// 47: Price Touches Lower BB + Bullish Candle
		{
			ID: 47, Name: "lower_bb_bullish_candle",
			DisplayName: "Price Touches Lower BB + Bullish Candle",
			Philosophy:  "Bullish candle at lower Bollinger Band confirms demand overcoming supply.",
			Category: "mean_reversion", Direction: types.LongOnly,
			Tags:       []string{"mean_reversion", "pattern", "long_only", "pattern", "time", "BBANDS", "CDL", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Below("low", c.ColRef("bb_lower")), c.AnyOf(c.CandleBullish("cdl_engulfing"), c.CandleBullish("cdl_harami"))},
			ExitLong:   []types.ConditionFn{c.Above("close", c.ColRef("bb_middle"))},
			ATRStopMult: 2.0, TimeStopBars: 20,
			RequiredIndicators: []string{"low", "bb_lower", "bb_middle", "cdl_engulfing", "cdl_harami", "atr_14"},
		},
		// 48: Upper BB + Bearish Candle
		{
			ID: 48, Name: "upper_bb_bearish_candle",
			DisplayName: "Upper BB + Bearish Candle",
			Philosophy:  "Bearish candle at upper Bollinger Band confirms supply overcoming demand.",
			Category: "mean_reversion", Direction: types.ShortOnly,
			Tags:       []string{"mean_reversion", "pattern", "short_only", "pattern", "time", "BBANDS", "CDL", "range_favor", "swing"},
			EntryShort: []types.ConditionFn{c.Above("high", c.ColRef("bb_upper")), c.AnyOf(c.CandleBearish("cdl_engulfing"), c.CandleBearish("cdl_shooting_star"))},
			ExitShort:  []types.ConditionFn{c.Below("close", c.ColRef("bb_middle"))},
			ATRStopMult: 2.0, TimeStopBars: 20,
			RequiredIndicators: []string{"high", "bb_upper", "bb_middle", "cdl_engulfing", "cdl_shooting_star", "atr_14"},
		},
		// 49: Slow MA Mean Reversion (to SMA50)
		{
			ID: 49, Name: "slow_ma_reversion",
			DisplayName: "Slow MA Mean Reversion (to SMA50)",
			Philosophy:  "Extreme deviation from slow MA with RSI filter captures position-scale reversions.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "long_short", "threshold", "time", "SMA", "ATR", "range_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.DeviationBelow("close", "sma_50", 2.0), c.Below("rsi_14", c.NumRef(40))},
			EntryShort: []types.ConditionFn{c.DeviationAbove("close", "sma_50", 2.0), c.Above("rsi_14", c.NumRef(60))},
			ExitLong:   []types.ConditionFn{c.Above("close", c.ColRef("sma_50"))},
			ExitShort:  []types.ConditionFn{c.Below("close", c.ColRef("sma_50"))},
			ATRStopMult: 2.5, TimeStopBars: 30,
			RequiredIndicators: []string{"close", "sma_50", "rsi_14", "atr_14"},
		},
		// 50: Pinch Reversion (ATR contraction then snap)
		{
			ID: 50, Name: "pinch_reversion",
			DisplayName: "Pinch Reversion",
			Philosophy:  "ATR contraction with low ADX signals coiling; RSI 50 cross triggers the snap.",
			Category: "mean_reversion", Direction: types.LongShort,
			Tags:       []string{"mean_reversion", "volatility", "long_short", "threshold", "time", "ATR", "RSI", "vol_contract", "swing"},
			EntryLong:  []types.ConditionFn{c.ATRBelowContractedSMA(0.80), c.Below("adx_14", c.NumRef(20)), c.WasBelowThenCrossesAbove("rsi_14", 50, 10)},
			EntryShort: []types.ConditionFn{c.ATRBelowContractedSMA(0.80), c.Below("adx_14", c.NumRef(20)), c.WasAboveThenCrossesBelow("rsi_14", 50, 10)},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("rsi_14", c.NumRef(50))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("rsi_14", c.NumRef(50))},
			ATRStopMult: 2.0, TimeStopBars: 25,
			RequiredIndicators: []string{"atr_14", "atr_sma_50", "adx_14", "rsi_14"},
		},
	}
}
