package strategy

// Trend strategies (IDs 1-25).

import (
	c "github.com/algomatic/strats100/go-strats/pkg/conditions"
	"github.com/algomatic/strats100/go-strats/pkg/types"
)

func trendStrategies() []*types.StrategyDef {
	return []*types.StrategyDef{
		// 1: EMA20/EMA50 Trend Cross
		{
			ID: 1, Name: "ema20_ema50_trend_cross",
			DisplayName: "EMA20/EMA50 Trend Cross",
			Philosophy:  "Classic dual-EMA crossover captures medium-term trend shifts.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "cross", "signal", "atr_stop", "EMA", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("ema_20", c.ColRef("ema_50")), c.Above("close", c.ColRef("ema_50"))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("ema_20", c.ColRef("ema_50")), c.Below("close", c.ColRef("ema_50"))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("ema_20", c.ColRef("ema_50"))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("ema_20", c.ColRef("ema_50"))},
			ATRStopMult: 2.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"ema_20", "ema_50", "atr_14"},
		},
		// 2: EMA50/EMA200 Golden/Death Cross
		{
			ID: 2, Name: "ema50_ema200_golden_death_cross",
			DisplayName: "EMA50/EMA200 Golden/Death Cross",
			Philosophy:  "Slow crossover captures major trend reversals with wide stops.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "cross", "signal", "atr_stop", "EMA", "ATR", "trend_favor", "position"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("ema_50", c.ColRef("ema_200"))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("ema_50", c.ColRef("ema_200"))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("ema_50", c.ColRef("ema_200"))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("ema_50", c.ColRef("ema_200"))},
			ATRStopMult: 2.5, TimeStopBars: 120,
			RequiredIndicators: []string{"ema_50", "ema_200", "atr_14"},
		},
		// 3: Price Above/Below KAMA Trend
		{
			ID: 3, Name: "price_above_below_kama",
			DisplayName: "Price Above/Below KAMA Trend",
			Philosophy:  "Adaptive moving average filters noise; price crossing KAMA signals trend change.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "threshold", "trailing", "KAMA", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("close", c.ColRef("kama_30"))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("close", c.ColRef("kama_30"))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("close", c.ColRef("kama_30"))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("close", c.ColRef("kama_30"))},
			ATRStopMult: 2.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"kama_30", "atr_14"},
		},
		// 4: MACD Line/Signal Cross with Trend Filter
		{
			ID: 4, Name: "macd_signal_cross_trend_filter",
			DisplayName: "MACD Line/Signal Cross with Trend Filter",
			Philosophy:  "MACD crossover filtered by ADX ensures entries only in trending markets.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "cross", "signal", "atr_stop", "MACD", "ADX", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("macd", c.ColRef("macd_signal")), c.Above("adx_14", c.NumRef(20))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("macd", c.ColRef("macd_signal")), c.Above("adx_14", c.NumRef(20))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("macd", c.ColRef("macd_signal"))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("macd", c.ColRef("macd_signal"))},
			ATRStopMult: 2.0,
			RequiredIndicators: []string{"macd", "macd_signal", "adx_14", "atr_14"},
		},
		// 5: MACD Histogram Zero-Line
		{
			ID: 5, Name: "macd_hist_zero_line",
			DisplayName: "MACD Histogram Zero-Line",
			Philosophy:  "Histogram zero-line cross captures momentum shifts earlier than MACD line cross.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "threshold", "trailing", "MACD", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("macd_hist", c.NumRef(0))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("macd_hist", c.NumRef(0))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("macd_hist", c.NumRef(0))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("macd_hist", c.NumRef(0))},
			ATRStopMult: 2.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"macd_hist", "atr_14"},
		},
		// 6: ADX Rising Trend Continuation (DI+/-)
		{
			ID: 6, Name: "adx_rising_di_continuation",
			DisplayName: "ADX Rising Trend Continuation (DI+/-)",
			Philosophy:  "Rising ADX with DI alignment confirms strengthening trend.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "threshold", "signal", "trailing", "ADX", "PLUS_DI", "MINUS_DI", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Above("plus_di_14", c.ColRef("minus_di_14")), c.Rising("adx_14", 3), c.Above("adx_14", c.NumRef(20))},
			EntryShort: []types.ConditionFn{c.Above("minus_di_14", c.ColRef("plus_di_14")), c.Rising("adx_14", 3), c.Above("adx_14", c.NumRef(20))},
			ExitLong:   []types.ConditionFn{c.CrossesAbove("minus_di_14", c.ColRef("plus_di_14"))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("plus_di_14", c.ColRef("minus_di_14"))},
			ATRStopMult: 2.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"adx_14", "plus_di_14", "minus_di_14", "psar", "atr_14"},
		},
		// 7: SAR Trend Ride
		{
			ID: 7, Name: "sar_trend_ride",
			DisplayName: "SAR Trend Ride",
			Philosophy:  "Parabolic SAR provides built-in trailing stop that accelerates with trend.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "threshold", "trailing", "SAR", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("close", c.ColRef("psar"))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("close", c.ColRef("psar"))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("close", c.ColRef("psar"))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("close", c.ColRef("psar"))},
			ATRStopMult: 2.0,
			RequiredIndicators: []string{"psar", "atr_14"},
		},
		// 8: TRIX Signal Cross
		{
			ID: 8, Name: "trix_signal_cross",
			DisplayName: "TRIX Signal Cross",
			Philosophy:  "Triple-smoothed EMA rate of change filters noise; signal cross confirms trend.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "cross", "signal", "atr_stop", "TRIX", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.TRIXCrossesAboveSMA()},
			EntryShort: []types.ConditionFn{c.TRIXCrossesBelowSMA()},
			ExitLong:   []types.ConditionFn{c.TRIXCrossesBelowSMA()},
			ExitShort:  []types.ConditionFn{c.TRIXCrossesAboveSMA()},
			ATRStopMult: 2.0,
			RequiredIndicators: []string{"trix_15", "atr_14"},
		},
		// 9: APO Momentum Cross
		{
			ID: 9, Name: "apo_momentum_cross",
			DisplayName: "APO Momentum Cross",
			Philosophy:  "Absolute Price Oscillator zero-line cross with EMA trend filter.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "cross", "signal", "atr_stop", "APO", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("apo", c.NumRef(0)), c.Above("close", c.ColRef("ema_50"))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("apo", c.NumRef(0)), c.Below("close", c.ColRef("ema_50"))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("apo", c.NumRef(0))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("apo", c.NumRef(0))},
			ATRStopMult: 2.0,
			RequiredIndicators: []string{"apo", "ema_50", "atr_14"},
		},
		// 10: ROC Break in Direction of SMA200
		{
			ID: 10, Name: "roc_break_sma200",
			DisplayName: "ROC Break in Direction of SMA200",
			Philosophy:  "Rate of Change zero-line break confirmed by long-term trend direction.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "threshold", "atr_stop", "time", "ROC", "SMA", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Above("close", c.ColRef("sma_200")), c.CrossesAbove("roc_10", c.NumRef(0))},
			EntryShort: []types.ConditionFn{c.Below("close", c.ColRef("sma_200")), c.CrossesBelow("roc_10", c.NumRef(0))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("roc_10", c.NumRef(0))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("roc_10", c.NumRef(0))},
			ATRStopMult: 2.0, TimeStopBars: 30,
			RequiredIndicators: []string{"roc_10", "sma_200", "atr_14"},
		},
		// 11: Momentum + Pullback to EMA20
		{
			ID: 11, Name: "momentum_pullback_ema20",
			DisplayName: "Momentum + Pullback to EMA20",
			Philosophy:  "Enter trending pullbacks at the fast EMA for high-probability continuation.",
			Category: "trend", Direction: types.LongOnly,
			Tags: []string{"trend", "long_only", "pullback", "trailing", "EMA", "ADX", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Above("close", c.ColRef("ema_50")), c.Above("adx_14", c.NumRef(20)), c.PullbackTo("ema_20", 0.5)},
			EntryShort: nil,
			ExitLong:   []types.ConditionFn{c.Below("close", c.ColRef("ema_20"))},
			ATRStopMult: 2.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"ema_20", "ema_50", "adx_14", "atr_14"},
		},
		// 12: Momentum + Pullback to BB Middle
		{
			ID: 12, Name: "momentum_pullback_bb_middle",
			DisplayName: "Momentum + Pullback to BB Middle",
			Philosophy:  "Bollinger middle band acts as dynamic support/resistance in trending markets.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "pullback", "trailing", "BBANDS", "ADX", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Above("adx_14", c.NumRef(20)), c.Above("close", c.ColRef("bb_middle")), c.PullbackTo("bb_middle", 0.5)},
			EntryShort: []types.ConditionFn{c.Above("adx_14", c.NumRef(20)), c.Below("close", c.ColRef("bb_middle")), c.PullbackBelow("bb_middle", 0.5)},
			ExitLong:   []types.ConditionFn{c.Below("close", c.ColRef("bb_middle"))},
			ExitShort:  []types.ConditionFn{c.Above("close", c.ColRef("bb_middle"))},
			ATRStopMult: 2.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"bb_middle", "adx_14", "atr_14"},
		},
		// 13: Super Trend-like ATR Channel
		{
			ID: 13, Name: "super_trend_atr_channel",
			DisplayName: "Super Trend-like ATR Channel",
			Philosophy:  "ATR channel around EMA captures strong breakouts beyond normal volatility.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "threshold", "trailing", "EMA", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CloseAboveUpperChannel("ema_20", 2.0)},
			EntryShort: []types.ConditionFn{c.CloseBelowLowerChannel("ema_20", 2.0)},
			ExitLong:   []types.ConditionFn{c.Below("close", c.ColRef("ema_20"))},
			ExitShort:  []types.ConditionFn{c.Above("close", c.ColRef("ema_20"))},
			ATRStopMult: 2.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"ema_20", "atr_14"},
		},
		// 14: Linear Regression Slope + Price Filter
		{
			ID: 14, Name: "linear_reg_slope_filter",
			DisplayName: "Linear Regression Slope + Price Filter",
			Philosophy:  "Linear regression slope quantifies trend direction; combined with SMA filter.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "threshold", "time", "atr_stop", "LINEARREG_SLOPE", "SMA", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Above("linearreg_slope_20", c.NumRef(0)), c.Above("close", c.ColRef("sma_50"))},
			EntryShort: []types.ConditionFn{c.Below("linearreg_slope_20", c.NumRef(0)), c.Below("close", c.ColRef("sma_50"))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("linearreg_slope_20", c.NumRef(0))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("linearreg_slope_20", c.NumRef(0))},
			ATRStopMult: 2.0, TimeStopBars: 40,
			RequiredIndicators: []string{"linearreg_slope_20", "sma_50", "atr_14"},
		},
		// 15: Aroon Trend Start
		{
			ID: 15, Name: "aroon_trend_start",
			DisplayName: "Aroon Trend Start",
			Philosophy:  "Aroon oscillator detects new trend initiation when one direction dominates.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "threshold", "signal", "atr_stop", "AROON", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("aroon_up_25", c.NumRef(70)), c.Below("aroon_down_25", c.NumRef(30))},
			EntryShort: []types.ConditionFn{c.CrossesAbove("aroon_down_25", c.NumRef(70)), c.Below("aroon_up_25", c.NumRef(30))},
			ExitLong:   []types.ConditionFn{c.CrossesAbove("aroon_down_25", c.NumRef(70))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("aroon_up_25", c.NumRef(70))},
			ATRStopMult: 2.0,
			RequiredIndicators: []string{"aroon_up_25", "aroon_down_25", "atr_14"},
		},
		// 16: Ichimoku-lite (EMA proxy)
		{
			ID: 16, Name: "ichimoku_lite",
			DisplayName: "Ichimoku-lite (EMA proxy)",
			Philosophy:  "EMA stack alignment (20>50>200) proxies Ichimoku cloud bullish conditions.",
			Category: "trend", Direction: types.LongOnly,
			Tags: []string{"trend", "long_only", "threshold", "trailing", "EMA", "ATR", "trend_favor", "swing"},
			EntryLong: []types.ConditionFn{c.Above("ema_20", c.ColRef("ema_50")), c.Above("ema_50", c.ColRef("ema_200")), c.Above("close", c.ColRef("ema_20"))},
			ExitLong:  []types.ConditionFn{c.AnyOf(c.Below("ema_20", c.ColRef("ema_50")), c.Below("close", c.ColRef("ema_50")))},
			ATRStopMult: 2.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"ema_20", "ema_50", "ema_200", "atr_14"},
		},
		// 17: Trend + Volatility Expansion Confirmation
		{
			ID: 17, Name: "trend_vol_expansion",
			DisplayName: "Trend + Volatility Expansion Confirmation",
			Philosophy:  "Breakout beyond BB bands with expanding width confirms genuine volatility expansion.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "volatility", "long_short", "breakout", "atr_stop", "atr_target", "BBANDS", "ADX", "ATR", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.Above("adx_14", c.NumRef(20)), c.BreaksAboveLevel("bb_upper"), c.BBWidthIncreasing(5)},
			EntryShort: []types.ConditionFn{c.Above("adx_14", c.NumRef(20)), c.BreaksBelowLevel("bb_lower"), c.BBWidthIncreasing(5)},
			ExitLong:   []types.ConditionFn{c.Below("close", c.ColRef("bb_middle"))},
			ExitShort:  []types.ConditionFn{c.Above("close", c.ColRef("bb_middle"))},
			ATRStopMult: 2.0, ATRTargetMult: 3.0,
			RequiredIndicators: []string{"adx_14", "bb_upper", "bb_lower", "bb_middle", "bb_width", "atr_14"},
		},
		// 18: PPO Signal Cross with Long-Term Filter
		{
			ID: 18, Name: "ppo_signal_cross",
			DisplayName: "PPO Signal Cross with Long-Term Filter",
			Philosophy:  "Percentage Price Oscillator normalises MACD; SMA200 filter ensures trend alignment.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "cross", "signal", "atr_stop", "PPO", "SMA", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.Above("close", c.ColRef("sma_200")), c.CrossesAbove("ppo", c.ColRef("ppo_signal"))},
			EntryShort: []types.ConditionFn{c.Below("close", c.ColRef("sma_200")), c.CrossesBelow("ppo", c.ColRef("ppo_signal"))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("ppo", c.ColRef("ppo_signal"))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("ppo", c.ColRef("ppo_signal"))},
			ATRStopMult: 2.0,
			RequiredIndicators: []string{"ppo", "ppo_signal", "sma_200", "atr_14"},
		},
		// 19: EMA Ribbon Compression Break
		{
			ID: 19, Name: "ema_ribbon_compression_break",
			DisplayName: "EMA Ribbon Compression Break",
			Philosophy:  "Tight EMA compression signals coiling energy; breakout indicates directional resolve.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "breakout", "long_short", "breakout", "atr_stop", "EMA", "ATR", "vol_contract_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.RibbonBreakLong(10, 0.5)},
			EntryShort: []types.ConditionFn{c.RibbonBreakShort(10, 0.5)},
			ExitLong:   []types.ConditionFn{c.RibbonExitLong(0.5)},
			ExitShort:  []types.ConditionFn{c.RibbonExitShort(0.5)},
			ATRStopMult: 2.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"ema_20", "ema_50", "atr_14"},
		},
		// 20: Trend Day Filter with VWAP Proxy
		{
			ID: 20, Name: "trend_day_vwap_proxy",
			DisplayName: "Trend Day Filter with VWAP Proxy",
			Philosophy:  "VWAP proxy with ADX and RSI filters identifies intraday trending conditions.",
			Category: "trend", Direction: types.LongOnly,
			Tags: []string{"trend", "long_only", "threshold", "time", "SMA", "ADX", "ATR", "trend_favor", "scalp"},
			EntryLong: []types.ConditionFn{c.Above("close", c.ColRef("typical_price_sma_20")), c.Above("adx_14", c.NumRef(20)), c.Above("rsi_14", c.NumRef(55))},
			ExitLong:  []types.ConditionFn{c.Below("close", c.ColRef("typical_price_sma_20"))},
			ATRStopMult: 1.5, TimeStopBars: 10,
			RequiredIndicators: []string{"typical_price_sma_20", "adx_14", "rsi_14", "atr_14"},
		},
		// 21: DI Pullback Entry
		{
			ID: 21, Name: "di_pullback_entry",
			DisplayName: "DI Pullback Entry",
			Philosophy:  "Enter trend pullbacks when RSI resets and DI direction is confirmed.",
			Category: "trend", Direction: types.LongOnly,
			Tags: []string{"trend", "long_only", "pullback", "signal", "trailing", "PLUS_DI", "MINUS_DI", "ADX", "ATR", "trend_favor", "swing"},
			EntryLong: []types.ConditionFn{c.Above("plus_di_14", c.ColRef("minus_di_14")), c.Above("adx_14", c.NumRef(20)), c.WasBelowThenCrossesAbove("rsi_14", 50, 5)},
			ExitLong:  []types.ConditionFn{c.CrossesAbove("minus_di_14", c.ColRef("plus_di_14"))},
			ATRStopMult: 2.0, TrailingATRMult: 2.0,
			RequiredIndicators: []string{"plus_di_14", "minus_di_14", "adx_14", "rsi_14", "atr_14"},
		},
		// 22: Trend Continuation After RSI Reset
		{
			ID: 22, Name: "trend_continuation_rsi_reset",
			DisplayName: "Trend Continuation After RSI Reset",
			Philosophy:  "RSI dip-and-recover in an uptrend signals exhausted sellers and fresh momentum.",
			Category: "trend", Direction: types.LongOnly,
			Tags: []string{"trend", "long_only", "pullback", "signal", "atr_stop", "RSI", "EMA", "ATR", "trend_favor", "swing"},
			EntryLong: []types.ConditionFn{c.Above("close", c.ColRef("ema_50")), c.WasBelowThenCrossesAbove("rsi_14", 50, 10)},
			ExitLong:  []types.ConditionFn{c.AnyOf(c.CrossesBelow("rsi_14", c.NumRef(45)), c.Below("close", c.ColRef("ema_50")))},
			ATRStopMult: 2.0,
			RequiredIndicators: []string{"ema_50", "rsi_14", "atr_14"},
		},
		// 23: Moving Average Envelope Break
		{
			ID: 23, Name: "ma_envelope_break",
			DisplayName: "Moving Average Envelope Break",
			Philosophy:  "ATR-based envelope around SMA captures momentum breakouts normalized for volatility.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "breakout", "long_short", "breakout", "atr_stop", "atr_target", "SMA", "ATR", "vol_expand", "swing"},
			EntryLong:  []types.ConditionFn{c.BreaksAboveSMAEnvelope("sma_20", 1.5)},
			EntryShort: []types.ConditionFn{c.BreaksBelowSMAEnvelope("sma_20", 1.5)},
			ExitLong:   []types.ConditionFn{c.Below("close", c.ColRef("sma_20"))},
			ExitShort:  []types.ConditionFn{c.Above("close", c.ColRef("sma_20"))},
			ATRStopMult: 2.0, ATRTargetMult: 3.0,
			RequiredIndicators: []string{"sma_20", "atr_14"},
		},
		// 24: HT Trendline Cross (Hilbert)
		{
			ID: 24, Name: "ht_trendline_cross",
			DisplayName: "HT Trendline Cross (Hilbert)",
			Philosophy:  "Hilbert Transform trendline adapts to dominant cycle; cross signals trend change.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "cross", "signal", "atr_stop", "HT_TRENDLINE", "ATR", "trend_favor", "swing"},
			EntryLong:  []types.ConditionFn{c.CrossesAbove("close", c.ColRef("ht_trendline"))},
			EntryShort: []types.ConditionFn{c.CrossesBelow("close", c.ColRef("ht_trendline"))},
			ExitLong:   []types.ConditionFn{c.CrossesBelow("close", c.ColRef("ht_trendline"))},
			ExitShort:  []types.ConditionFn{c.CrossesAbove("close", c.ColRef("ht_trendline"))},
			ATRStopMult: 2.0,
			RequiredIndicators: []string{"ht_trendline", "atr_14"},
		},
		// 25: Three-Bar Trend with EMA Filter
		{
			ID: 25, Name: "three_bar_trend_ema",
			DisplayName: "Three-Bar Trend with EMA Filter",
			Philosophy:  "Short-term momentum (3 consecutive directional closes) with EMA trend confirmation.",
			Category: "trend", Direction: types.LongShort,
			Tags: []string{"trend", "long_short", "threshold", "time", "atr_stop", "EMA", "ATR", "trend_favor", "scalp"},
			EntryLong:  []types.ConditionFn{c.Above("close", c.ColRef("ema_50")), c.ConsecutiveHigherCloses(3)},
			EntryShort: []types.ConditionFn{c.Below("close", c.ColRef("ema_50")), c.ConsecutiveLowerCloses(3)},
			ExitLong:   []types.ConditionFn{c.ConsecutiveLowerCloses(2)},
			ExitShort:  []types.ConditionFn{c.ConsecutiveHigherCloses(2)},
			ATRStopMult: 1.5, TimeStopBars: 8,
			RequiredIndicators: []string{"ema_50", "atr_14"},
		},
	}
}
